# - name: Download Zabbix 5.0 deb
#   get_url:
#     url: 'https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+{{ansible_distribution_release}}_all.deb'
#     dest: '/tmp/zabbix.deb'

# - name: Install Zabbix
#   apt:
#     deb: '/tmp/zabbix.deb'

- name: Install Packages
  apt:
    pkg:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-agent
      - python3-pexpect
      - python3-pymysql
      - fonts-mplus
      - snmp
      - snmp-mibs-downloader
      
    update_cache: 'yes'

- name: Initialize MySQL
  shell: |
    mysql -e "SET PASSWORD FOR root@localhost = PASSWORD('{{mysql_pass}}'); FLUSH PRIVILEGES;" 
    printf "{{mysql_pass}}\n n\n n\n n\n y\n y\n y\n" | sudo mysql_secure_installation

- name: check if DB exists
  shell: mysql -uroot -p{{mysql_pass}} -e "SHOW DATABASES;" | grep zabbix
  register: db_exist
  failed_when: db_exist.rc == 2

- name: Create MySQL databases
  mysql_db:
    name: 'zabbix'
    encoding: 'utf8'
    collation: 'utf8_bin'
    login_user: 'root'
    login_password: '{{mysql_pass}}'
  no_log: 'yes'
  when: db_exist.rc != 0

- name: Add MySQL user
  mysql_user:
    name: zabbix
    password: zabbix
    priv: 'zabbix.*:ALL'
    login_user: 'root'
    login_password: '{{mysql_pass}}'
  no_log: 'yes'
  when: db_exist.rc != 0

- name: Initialze Database
  shell: |
     mysql -uroot -p{{mysql_pass}} zabbix -e "set global innodb_strict_mode='OFF'"
     zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -pzabbix zabbix
     mysql -uroot -p{{mysql_pass}} zabbix -e "set global innodb_strict_mode='ON'"
  when: db_exist.rc != 0

- name: Setting Zabbix server
  lineinfile:
    path: '/etc/zabbix/zabbix_server.conf'
    regexp: '{{item.regexp}}'
    line: '{{item.line}}'
  with_items:
    - regexp: '^DBPassword=.*$'
      line: 'DBPassword=zabbix'
    - regexp: '^#? *StartIPMIPollers=.*$'
      line: 'StartIPMIPollers=1'
  notify:
    restart zabbix server
    
- name: Enable Zabbix service
  systemd:
    name: '{{item}}'
    enabled: yes
  with_items:
    - zabbix-server.service
    - zabbix-agent.service

- name: Setting Zabbix frontend
  lineinfile:
    path: '/etc/zabbix/apache.conf'
    regexp: '^ +# php_value date.timezone .*$'
    line: '        php_value date.timezone Asia/Tokyo'
  notify:
    restart apache

- name: Setting Font
  file: 
    src: '/usr/share/fonts/truetype/mplus/mplus-1p-regular.ttf'
    dest: '/etc/alternatives/zabbix-frontend-font'
    state: 'link'
    force: 'yes'

- name: Setting SNMP
  lineinfile:
    path: '/etc/snmp/snmp.conf'
    regexp: '^mibs.*$'
    line: 'mibs all'

