- name: Install Packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - ntp

- name: Generate Locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_US.UTF-8
    - ja_JP.UTF-8

- name: Setting Sysctl
  template:
    src=sysctl/sysctl.conf.j2 dest=/etc/sysctl.conf
    owner=root
    group=root
    mode=0440
  notify:
    reload sysctl

- name: Setting Sudo
  template:
    src=sudo/sudoers.j2 dest=/etc/sudoers
    owner=root
    group=root
    mode=0440

- name: Setting SSHD
  template:
    src=ssh/sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
    restart sshd

- name: Setting Rsyslog
  template:
    src=rsyslog/{{ item.name }}.j2 dest={{ item.path }}/{{ item.name }}
  with_items:
    - { name: rsyslog.conf, 	    path: /etc }
    - { name: 10-equipment.conf,  path: /etc/rsyslog.d }
  notify: restart rsyslog

- name: Setting NTPD server
  template:
    src=ntp/ntp.conf-server.j2 dest=/etc/ntp.conf
    owner=ntp
    group=ntp
  when: ntp_server is defined
  notify: restart ntp

- name: Setting NTPD client
  template:
    src=ntp/ntp.conf-client.j2 dest=/etc/ntp.conf
    owner=ntp
    group=ntp
  when: ntp_server is not defined
  notify: restart ntp

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
