- name: reload sysctl
  shell: sysctl -p

- name: restart sshd
  service: name=ssh state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted
  
- name: restart ntp
  service: name=ntp state=restarted

- name: restart timesyncd
  systemd: name=systemd-timesyncd.service state=restarted

- name: update grub
  shell: update-grub
  
# Local Variables:
# mode: yaml
# tab-width: 4
# End:
