- name: reload mount
  mount:
    name: mount -a
    src: LABEL=root
    fstype: ext4
    state: present

- name: load kernel modules
  systemd:
    name: systemd-modules-load.service
    state: restarted
    
- name: restart samba
  service: name=smbd state=restarted

- name: restart hddtemp
  service: name=hddtemp state=restarted
  
- name: restart collectd
  service: name=collectd state=restarted
  
- name: update mail alias
  shell: newaliases

- name: restart apcupsd
  service: name=apcupsd state=restarted

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
