- name: reload mount
  mount:
    name: mount -a
    src: LABEL=root
    state: present

- name: restart samba
  service: name=smbd state=restarted

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
