- name: reload mount
  mount:
    name: mount -a
    src: LABEL=root
    fstype: ext4
    state: present

- name: load zfs
  shell: modprobe zfs
    
- name: restart samba
  service: name=smbd state=restarted

- name: restart hddtemp
  service: name=hddtemp state=restarted
  
- name: restart collectd
  service: name=collectd state=restarted
  
- name: update mail alias
  shell: newaliases

  
# Local Variables:
# mode: yaml
# tab-width: 4
# End:
