- name: Install Packages
  become: "{{ should_be_root }}"
  package:
    name:
      - "{{ 'emacs-nox' if ansible_pkg_mgr != 'homebrew' else 'emacs' }}"
      - zsh
      - tmux
      - keychain
      - "{{ 'silversearcher-ag' if ansible_pkg_mgr != 'homebrew' else 'the_silver_searcher' }}"
      - autojump
      - git
      - tig
      - htop
      - cmigemo
      - colordiff

- name: Setting dircolors
  become: no
  template:
    src=dircolors/dircolors.j2 dest=~/.dircolors

- name: Setting tmux
  become: no
  template:
    src=tmux/tmux.conf.j2 dest=~/.tmux.conf

- name: Setting Zsh
  become: no
  template:
    src=zsh/{{ item }}.j2 dest=~/.{{ item }}
  with_items:
    - zshenv
    - zshrc

- name: Setting zplug
  become: no
  git:
    repo: https://github.com/zplug/zplug.git
    dest: .zplug

- name: Settign Emacs (create directory)
  become: no
  file:
    path=~/.emacs.d
    state=directory

- name: Setting Emacs
  become: no
  template:
    src=emacs/init.el.j2 dest=~/.emacs.d/init.el

- name: Settign Emacs for root (create directory)
  file:
    path=/root/.emacs.d
    state=directory
  when: should_be_root

- name: Setting Emacs for root
  template:
    src=emacs/init.el.j2 dest=/root/.emacs.d/init.el
  when: should_be_root

- name: Setting Default Shell
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: /bin/zsh
  when: ansible_pkg_mgr != 'homebrew'

- name: Setting Git
  become: no
  template:
    src=git/gitconfig.j2 dest=~/.gitconfig

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
