- name: Install Packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - ansible
    - tmux
    - keychain
    - emacs24-nox
    - git
    - cmigemo
    - migemo-el
    - develock-el
    - autojump

- name: Setting dircolors
  become: no
  template:
    src=dircolors/dircolors.j2 dest=~/.dircolors

- name: Setting tmux
  become: no
  template:
    src=tmux/tmux.conf.j2 dest=~/.tmux.conf

- name: Setting Zsh
  become: no
  template:
    src=zsh/{{ item }}.j2 dest=~/.{{ item }}
  with_items:
    - zshenv
    - zshrc



# - name: Setting zplug
#   become: no
#   shell: curl -sL zplug.sh/installer | zsh

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
