- name: Install Packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - emacs-nox
    - zsh
    - tmux
    - keychain
    - silversearcher-ag
    - autojump
    - git
    - tig
    - htop
    - cmigemo

- name: Setting dircolors
  become: no
  template:
    src=dircolors/dircolors.j2 dest=~/.dircolors

- name: Setting tmux
  become: no
  template:
    src=tmux/tmux.conf.j2 dest=~/.tmux.conf

- name: Setting Zsh
  become: no
  template:
    src=zsh/{{ item }}.j2 dest=~/.{{ item }}
  with_items:
    - zshenv
    - zshrc

- name: Setting zplug
  become: no
  git:
    repo: https://github.com/zplug/zplug.git
    dest: .zplug

- name: Settign Emacs (create directory)
  become: no
  file:
    path=~/.emacs.d
    state=directory

- name: Setting Emacs
  become: no
  template:
    src=emacs/init.el.j2 dest=~/.emacs.d/init.el

- name: Settign Emacs for root (create directory)
  become: yes
  file:
    path=/root/.emacs.d
    state=directory
    
- name: Setting Emacs for root
  become: yes
  template:
    src=emacs/init.el.j2 dest=/root/.emacs.d/init.el

- name: Setting Default Shell
  become: yes
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: /bin/zsh

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
