- hosts: all

  become: yes

  roles:
    - common
    - dev

  handlers:

  tasks:
    - name: Install Packages
      apt:
        update-cache=yes
        pkg={{ item }}
        state=present
      with_items:
        - emacs24-nox
        - tmux
        - git
        - zsh
        - lsb-release
