- hosts: dhcp
  vars:
    ntp_server: true

  vars_files: 
    - host_config.yml

  become: yes

  roles:
    - common
    - dns
    - dhcp

  tasks:
    - name: Install Packages - server
      apt:
        update-cache=yes
        pkg={{ item }}
        state=present
      with_items:
        - postfix

  handlers:


