- hosts: dhcp
  vars:
    ntp_server: true

  vars_files: 
    - host_config.yml
  sudo: yes

  roles:
    - common
    - dns
    - dhcp

  tasks:
    - name: Install Packages - client
      apt:
        update-cache=yes
      apt: 
        pkg={{ item }}
        state=present
      with_items:
        - emacs24-nox
        - tmux
        - git
        - zsh
        - lsb-release

    - name: Install Packages - server
      apt:
        update-cache=yes
      apt: 
        pkg={{ item }}
        state=present
      with_items:
        - postfix


  handlers:





