- hosts: dhcp
  vars_files: 
    - host_config.yml
  sudo: yes

  roles:
    - common

  tasks:
    - name: Install Packages - client
      apt:
        update-cache=yes
      apt: 
        pkg={{ item }}
        state=present
      with_items:
        - emacs24-nox
        - tmux
        - git
        - zsh
        - lsb-release

    - name: Install Packages - server
      apt:
        update-cache=yes
      apt: 
        pkg={{ item }}
        state=present
      with_items:
        - isc-dhcp-server
        - bind9
        - ntp
        - postfix

    - name: Setting Network
      template:
        src=templates/network/interfaces.dhcp.j2 dest=/etc/network/interfaces


    - name: Setting DHCPD - copy configuration
      template:
        src=templates/dhcp/dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf
      notify:
        restart dhcpd

    - name: Setting BIND - copy configuration
      template:
        src=templates/bind/{{ item.name }}.j2 dest=/etc/bind/{{ item.name }}
        owner={{ item.owner }}
        group={{ item.group }}
      with_items:
        - { name: named.conf, 		owner: root, group: bind }
        - { name: named.conf.options, 	owner: root, group: bind }
        - { name: named.conf.zones,	owner: root, group: bind }
        - { name: db.127,		owner: root, group: bind }
        - { name: db.local,		owner: root, group: bind }
      notify: restart bind

    - stat: path=/var/cache/bind/db.{{ network.domain }}-internal
      register: bind_local_db

    - name: Setting BIND - copy local db
      template:
        src=templates/bind/{{ item }}.j2 dest=/var/cache/bind/{{ item }}
        owner=bind
        group=bind
      with_items:
        - db.{{ network.zone }}
        - db.{{ network.domain }}-internal
      when: bind_local_db.stat.md5 is not defined
      notify: restart bind

    - name: Setting BIND - make directory
      file:
        path=/var/log/named state=directory
        owner=bind
        group=bind
      notify: restart bind

    - name: Setting NTPD
      template:
        src=templates/ntp/ntp.conf.j2 dest=/etc/ntp.conf
        owner=ntp
        group=ntp
      notify: restart ntp

  handlers:

    - name: restart dhcpd
      service: name=isc-dhcp-server state=restarted

    - name: restart bind
      service: name=bind9 state=restarted

    - name: restart ntp
      service: name=ntp state=restarted



