- name: Install Packages
  apt:
    pkg: [ 'apcupsd', 'nut', 'nut-client' ]
    state: present

- name: Setting NUT - nut.conf
  replace:
    path: /etc/nut/nut.conf
    regexp: '^#?MODE=.*'
    replace: 'MODE=netserver'

- name: Setting NUT - ups.conf
  blockinfile:
    dest: '/etc/nut/ups.conf'
    content: |
      [bl50t]
      driver = blazer_usb
      port = /dev/ups
      desc = "Omron UPS BL50T"
      vendorid = 0590
      productid = 00CB
      subdriver = ippon
      default.battery.voltage.high = 27.5
      default.battery.voltage.low = 23.3
    insertbefore: EOF

- name: Setting NUT - upsd.conf
  blockinfile:
    dest: '/etc/nut/upsd.conf'
    content: |
      LISTEN 127.0.0.1
      LISTEN {{ ansible_default_ipv4.address }}
    insertbefore: EOF
  notify: restart nut-server

- name: Setting NUT - upsd.users
  blockinfile:
    dest: '/etc/nut/upsd.users'
    content: |
      [upsmon]
      password = upspass
      upsmon master
    insertbefore: EOF

- name: Setting NUT - upsmon.conf
  blockinfile:
    dest: '/etc/nut/upsmon.conf'
    content: |
      MONITOR bl50t@localhost 1 upsmon upspass master
    insertbefore: EOF

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
