- name: Install Packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - samba
    - postfix
    - zfsutils-linux
    - collectd
    - hddtemp
    - nfs-kernel-server
    - prometheus-node-exporter

- name: Setting Kernel Modules
  lineinfile:
    dest=/etc/modules-load.d/modules.conf
    line={{ item }}
  with_items:
    - zfs
    - acpi_ipmi
  notify:
    load kernel modules

- name: Setting ZFS Permission
  file:
    path=/dev/zfs owner=root group=sudo mode=0660

- name: Setting ZED
  replace:
    dest=/etc/zfs/zed.d/zed.rc
    regexp='^#ZED_NOTIFY_VERBOSE=0'
    replace='ZED_NOTIFY_VERBOSE=1'

- name: Create Mount Point
  file:
    path={{ item }} state=directory
  with_items:
    - /storage
    - /backup

- name: Setting mount
  template:
    src=mount/fstab.j2 dest=/etc/fstab
  notify:
    reload mount

- name: Setting Samba
  template:
    src=samba/smb.conf.j2 dest=/etc/samba/smb.conf
  notify:
    restart samba

- name: Setting Postfix
  lineinfile:
    dest={{item.dest}}
    regexp={{item.regexp}}
    line={{item.line}}
  with_items:
    - { dest: '/etc/postfix/main.cf', regexp: '^relayhost =.*', line: "relayhost = [mail.{{network.domain}}]" }
    - { dest: '/etc/aliases', regexp: '^root:.*', line: "root: {{network.root_mail}}" }
  notify:
    update mail alias

# - name: Disable multipath
#   blockinfile:
#     dest: /etc/multipath.conf
#     insertafter: '}'
#     content: |
#       blacklist {
#           devnode "^sd[a-z]"
#       }

- name: Setting Hddtemp
  replace:
    dest=/etc/default/hddtemp regexp='^RUN_DAEMON=.*$' replace='RUN_DAEMON="true"'
  notify:
    restart hddtemp

- name: Setting Collectd
  template:
    src={{item.src}} dest={{item.dest}} mode={{item.mode}}
  with_items:
    - { src: 'collectd/collectd.conf.j2', dest: '/etc/collectd/collectd.conf', mode: '0644' }
    - { src: 'collectd/zpool_df.py.j2', dest: '/usr/lib/collectd/zpool_df.py', mode: '0755' }
  notify:
    restart collectd

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
