- name: Install Packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - samba
    - postfix
    - zfsutils-linux
    - collectd
    - hddtemp

- name: Setting Kernel Modules
  lineinfile:
    dest=/etc/modules line=zfs
  notify:
    load zfs

- name: Setting ZFS Permission
  file:
    path=/dev/zfs owner=root group=sudo mode=0660

- name: Create Mount Point
  file:
    path={{ item }} state=directory
  with_items:
    - /storage
    - /backup

- name: Setting mount
  template:
    src=mount/fstab.j2 dest=/etc/fstab
  notify:
    reload mount

- name: Setting Samba
  template:
    src=samba/smb.conf.j2 dest=/etc/samba/smb.conf
  notify:
    restart samba

- name: Setting Postfix
  lineinfile:
    dest={{item.dest}} line={{item.line}}
  with_items:
    - { dest: '/etc/postfix/main.cf', line: "relayhost = [mail.{{network.domain}}]" }
    - { dest: '/etc/aliases', line: "root: {{network.root_mail}}" }
  notify:
    update mail alias

- name: Setting Hddtemp
  replace:
    dest=/etc/default/hddtemp regexp='^RUN_DAEMON=.*$' replace='RUN_DAEMON="true"'
  notify:
    restart hddtemp

- name: Setting Collectd
  template:
    src={{item.src}} dest={{item.dest}} mode={{item.mode}}
  with_items:
    - { src: 'collectd/collectd.conf.j2', dest: '/etc/collectd/collectd.conf', mode: '0644' }
    - { src: 'collectd/zpool_df.py.j2', dest: '/usr/lib/collectd/zpool_df.py', mode: '0755' }
  notify:
    restart collectd

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
